#+TITLE: dchan - distributed channel
#+AUTHOR: Tiago Natel de Moura
#+DATE: {{{time(%Y-%m-%d)}}}

#+STARTUP: overview
#+TAGS: PROJECT(p)
#+STARTUP: hidestars

#+INCLUDE: "orgconf/latex.setup"
#+SETUPFILE: orgconf/theme-bigblow.setup

#+INCLUDE: "README.org" :minlevel 1

#+INCLUDE: "docs/comparisons.org" :minlevel 1

* API
#+INCLUDE: "docs/api.org" :minlevel 2

* Terminology

This document uses a number of terms to refer to the roles played by
participants in, and objects of, the Dchan communication.

- goroutine: Go lightweight threads that represent anonymous processes
  in the CSP terminology.
- channel: Entity shared between processes whose purpose is to provide
  means of communication.
- Rprocess: Reader goroutine of a read 9P request.
- Wprocess: Writer goroutine of a write 9P request.

* Architecture
#+INCLUDE: "docs/arch.org" :minlevel 2

* Makefile

First of all, we need a Makefile to build this document and source
code.

The most used commands are:

- **make** to make a full rebuild of everything.
- **make tangle** to extract source code
- **make build** to build dchan software

#+BEGIN_SRC makefile :tangle Makefile :comments link
.PHONY: build clean clean-source clean-latex tangle test test-proxy test-dchan


# To install `dchan', type `make' and then `make install'.
BIN_DIR=/usr/local/bin
DCHAN_SRC=$(wildcard unix/dchan/*.org)
PROXY_SRC=unix/proxy/proxy.org
TEST_SRC=$(wildcard unix/testing/*.org)
OBJS=	unix/dchan/dchan \
	unix/proxy/proxy
DOC_BOOK=dchan.org
HTMLS=$(patsubst %.org,%.html,$(DOC_BOOK))
TXTS=$(patsubst %.org,%.txt,$(DOC_BOOK))
PDFS=$(patsubst %.org,%.pdf,$(DOC_BOOK))

all: tangle clean tangle test $(HTMLS) $(TXTS) $(PDFS)

clean-latex:
	rm -f *.blg *.bbl *.tex *.odt *.toc *.out *.aux

clean-source:
	-cd unix/dchan/ && make clean
	-cd unix/proxy/ && make clean

clean: clean-latex clean-source
	rm -f *.pngt
	rm -f *.txt *.html *.pdf *.odt
	rm -f *.log

%.html: %.org
	org2html $<

%.txt: %.org
	org2txt $<

%.pdf: %.org
	org2pdf $<
	-pdflatex dchan.tex
	bibtex dchan
	pdflatex dchan.tex
	pdflatex dchan.tex

tangle:
	org-tangle $(DOC_BOOK) && \
	org-tangle $(TEST_SRC) && \
	org-tangle $(DCHAN_SRC) && \
	org-tangle $(PROXY_SRC)

build: tangle
	cd unix/dchan/ && make build
	cd unix/proxy/ && make build

doc: $(HTMLS) $(PDFS) $(TXTS)

test-dchan: tangle
	cd unix/dchan/ && make test

test-proxy: tangle
	cd unix/proxy/ && make test

test: tangle test-dchan test-proxy

install:
	cp $(OBJS) $(BIN_DIR)

#+END_SRC

# Testing infrastructure
#+INCLUDE: "unix/testing/acceptance.org" :minlevel 1

* Development
#+INCLUDE: "unix/dchan/dchan.org" :minlevel 2

#+INCLUDE: "unix/proxy/proxy.org" :minlevel 2

* Work in progress

#+INCLUDE: "TODO.org"

* Bibliography

\bibliographystyle{plainnat}
\bibliography{./dchan}
